services:
  - type: worker
    name: google-placeid-bot
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PROVIDER
        value: finder
      - key: GOOGLE_API_KEY
        sync: false
      - key: SALES_WEBHOOK_URL
        value: https://discord.com/api/webhooks/1549913214660116553/cjU12LbwGSmInkfFSytO0hKFN1--yjIYa7mHfmklyIWQqOcspzsyyJ1VzxVjQT5u_nyP
      - key: GUILD_ID
        value: "1376191955511410688"
      - key: SALES_CATEGORY_ID
        value: "1390861758880682055"
      - key: OWNER_ID
        value: "1306929787033354250"
      - key: OWNER_NAME
        value: Marcos V.
      - key: CACHE_TTL
        value: "86400"
      - key: MAX_RESULTS
        value: "5"
